# Generated by Django 3.0.7 on 2020-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='investor_type',
            field=models.IntegerField(),
        ),
    ]
