# Generated by Django 3.0.7 on 2020-07-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_auto_20200706_0616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorType',
        ),
        migrations.AlterField(
            model_name='document',
            name='investor_type',
            field=models.CharField(choices=[(1, '상장기업'), (2, '비상장기업'), (3, '개인사업자')], max_length=1),
        ),
    ]
