# Generated by Django 3.0.7 on 2020-07-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_auto_20200706_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='investor_type',
        ),
    ]
