# Generated by Django 3.0.7 on 2020-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_document_investortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='InvestorType',
            field=models.CharField(choices=[('1', '상장기업'), ('2', '비상장기업'), ('3', '개인사업자')], max_length=10),
        ),
    ]
