# Generated by Django 3.0.7 on 2020-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0009_remove_document_investortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='asset',
            field=models.TextField(),
        ),
    ]
