# Generated by Django 3.0.7 on 2020-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0010_auto_20200706_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='InvestorType',
            field=models.CharField(choices=[('1', '상장기업'), ('2', '비상장기업'), ('3', '개인사업자')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
